### PR TITLE
Implement dashboard API & make frontend container dynamic

### PR DESCRIPTION
**Pull request by din0s**
## About
This PR contains the backend implementation for the data needed by the dashboard container, as well as an update to the frontend to rely on the API instead of a hardcoded JSON file.

## Backend implementation
The client sends an **authorized** GET request to `/api/users/me/dashboard` and we return a response with the following 4 lists:
* **next**: The user's next actions (up to 3), for which they've stated that they want to attend.
* **saved**: The user's saved actions.
* **teams**: The teams owned by the user, along with their most recently created action.
* **recommended**: A *curated* list of actions recommended to the user, based on the teams that they follow and the actions that they've explicitly shown interest in (attend/save).

## Empty dashboard prompts
~~Maybe we should prompt the user to follow some teams and attend some actions when all of the lists are empty (since otherwise, they'll be seeing a blank page).~~
This has now been implemented and a dashboard with no next actions will display a prompt to discover new actions, while no recommendations will prompt the user to follow a team.

As a bonus, the team selector will only appear for users that own at least one team.

### CODE REVIEW

**Comment by SotirisFtiakas** [comment]
I think that prompting the users to follow some teams is a good idea. I'm not sure about the way we will prompt them though. Should we have a prompt message and a link, or some kind of a button? 

*Note*: shouldn't the height of the page be minimum 100% of the screen height? When no activities and teams are displayed, the page height is small, moving the footer upwards.

**Comment by din0s** [comment]
@SotirisFtiakas
I've added some prompts for users that have no next/recommended actions. LMK what you think.

Also, for the height discrepancies, I think that we should have a look at it all over the website (since other pages have similar issues as well) when everything is fully functional.

**Comment by SotirisFtiakas** [comment]
@din0s yes the prompting links are fine, I think it would be even better if the "No ___ actions" messages were horizontally aligned to the panels and had a little bigger font than the links, but that's just my personal preference.
(Maybe even vertically aligned, especially for mobile versions; not sure if it would look better though, just a thought) 

Also I noticed that the saved actions panel for under <1400 px width, is a little smaller (left-right) than the other two panels.

**Comment by din0s** [comment]
@SotirisFtiakas:
> Also I noticed that the saved actions panel for under <1400 px width, is a little smaller (left-right) than the other two panels.

This is by design since its content has way less information than the other two panels and it looks empty when it's full-width like they are. If it's not looking good then IMO we should consider shrinking it even more, not the other way around.

**Pull request merged**
